Vagrant.configure("2") do |config|

  config.vm.box = "puppetlabs/centos-7.2-64-nocm"

  config.vm.network "forwarded_port", guest: 5601, host: 5601
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.provision "shell", path: "init_docker.sh"
  config.vm.provision "shell", inline: "usermod -G docker vagrant"

  config.vm.provision "file", source: "../docker-compose.yml", destination: "docker-compose.yml"
  config.vm.synced_folder "../conf/logstash", "/home/vagrant/conf/logstash"
  config.vm.provision "shell", inline: "docker-compose up -d"
end
